# Generated by Django 3.2.5 on 2021-11-25 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=128)),
                ('image_id', models.CharField(max_length=1024, null=True)),
            ],
            options={
                'db_table': 'exSubscription',
            },
        ),
        migrations.CreateModel(
            name='plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=256)),
                ('cycle', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(help_text='user ID', max_length=128, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=128)),
                ('plan_price', models.CharField(max_length=128)),
                ('cycle', models.CharField(max_length=128)),
                ('start_date', models.DateTimeField(max_length=128)),
                ('service_id', models.CharField(max_length=128, null=True)),
                ('end_date', models.DateTimeField(max_length=128, null=True)),
                ('image_id', models.CharField(max_length=1024, null=True)),
                ('user_id', models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='user_api.user')),
            ],
            options={
                'db_table': 'Subscription',
            },
        ),
    ]
