# Generated by Django 3.2.5 on 2021-11-25 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', max_length=128, on_delete=django.db.models.deletion.CASCADE, to='user_api.user'),
        ),
    ]
