# Generated by Django 3.2.5 on 2021-11-25 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_alter_subscription_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='exsub_id',
            field=models.ForeignKey(db_column='exsub_id', default='', max_length=128, on_delete=django.db.models.deletion.CASCADE, to='user_api.exsubscription'),
        ),
        migrations.AlterModelTable(
            name='plan',
            table='plan',
        ),
    ]
