# Generated by Django 3.2.5 on 2021-11-25 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_auto_20211125_0305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='exSubscription',
            new_name='DefaultSubscription',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='exsub_id',
        ),
        migrations.AddField(
            model_name='plan',
            name='default_sub_id',
            field=models.ForeignKey(db_column='default_sub_id', default='', max_length=128, on_delete=django.db.models.deletion.CASCADE, to='user_api.defaultsubscription'),
        ),
        migrations.AlterModelTable(
            name='defaultsubscription',
            table='DefaultSubscription',
        ),
        migrations.AlterModelTable(
            name='plan',
            table='Plan',
        ),
    ]
